export default {
    "FETCH_TODOS": "FETCH_TODOS",
    "TOGGLE_TODO": "TOGGLE_TODO",
    "FILTER_TODOS": "FILTER_TODOS",
    "FETCH_TODOS_SKELETON_LAODING": "FETCH_TODOS_SKELETON_LAODING",
    "ADD_TODO": "ADD_TODO",
    "RMOVE_TODO": "RMOVE_TODO",
    "UPDATE_TODO": "UPDATE_TODO"
}